### PR TITLE
CI: Build matrix

### PR DESCRIPTION
**Pull request by tuxuser**
* build matrix
* Error if artifact path contains no files
* Enable OSX builds

### CODE REVIEW

**Comment by tuxuser** [comment]
On the mobile site it's tough to resolve merge conflicts..

**Comment by tuxuser** [comment]
Ready to be merged

**Comment by Natetronn** [comment]
Looks great, thank you!

Please add `osx-x64` to RepackinatorUI.csproj along with the other two RIDs:

https://github.com/Team-Resurgent/Repackinator/blob/main/RepackinatorUI/RepackinatorUI.csproj#L13

**Comment by tuxuser** [comment]
Done

**Comment by Natetronn** [comment]
Sure, that would be a nice addition, thanks.

**Comment by tuxuser** [comment]
There we go

**Comment by Natetronn** [comment]
One last one, if you don't mind?

Can you add the `-p:Platform=x64` flag to the dotnet publish command and update the various paths accordingly? Perhaps via another strategy matrix of arch(itecture). With the included architecture, the various paths should now look something like the following, with the added architecture in the path:

`${{ github.workspace }}/${{ matrix.project }}/bin/${{ matrix.arch }}/Release/net6.0/${{ matrix.os_flavor }}/publish/${{ matrix.project }}`

```
    strategy:
      matrix:
        arch: [x64]
```

**Comment by tuxuser** [comment]
Check

**Comment by HoRnEyDvL** [comment]
Thanks for fixing multi platform support.

**Comment by Natetronn** [comment]
Thank you for the contribution, @tuxuser!

**Pull request merged**
